workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk
      node: 20
      flutter: none
      xcode: none

    scripts:
      - name: Install Gradle Wrapper
        script: |
          mkdir -p android
          cd android
          wget https://services.gradle.org/distributions/gradle-7.5.1-bin.zip -O gradle.zip
          unzip -q gradle.zip -d $HOME/gradle
          export PATH=$HOME/gradle/gradle-7.5.1/bin:$PATH
          gradle wrapper --gradle-version 7.5.1
          cd ..

      - name: Install npm dependencies
        script: |
          npm install

      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
