workflows:
  android-build:
    name: Android Build
    max_build_duration: 120
    environment:
      node: 18  # 匹配项目使用的Node.js版本
      java: 17  # 匹配项目Java版本
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Checkout repository
        script: |
          git checkout $CM_BRANCH
          git pull

      - name: Cache npm dependencies
        script: "npm cache verify"  # 修正为字符串类型
        
      - name: Install dependencies
        script: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
        # 将npm缓存配置移至安装依赖步骤
        cache:
          key: npm-${{ hashFiles('**/package-lock.json') }}
          paths:
            - ~/.npm
            - node_modules

      - name: Expo prebuild (生成原生代码)
        script: |
          # 预构建生成Android原生目录
          npx expo prebuild --platform android --clean

      - name: Fix gradlew permissions
        script: "chmod +x android/gradlew"  # 修正为字符串类型

      - name: Prepare JS bundle
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

      - name: Build APK with Gradle
        script: |
          cd android
          # 构建debug版本
          ./gradlew clean assembleDebug --stacktrace
        # 添加Gradle缓存配置
        cache:
          key: gradle-${{ checksum 'android/build.gradle' }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
            - ~/.android/build-cache
        
    artifacts:
      - android/app/build/outputs/apk/**/*.apk  # 上传构建产物
    
