workflows:
  # 通用环境配置
  environment_common:
    environment:
      vars:
        # 应用基本信息
        APP_NAME: "YourAppName"
        BUNDLE_ID: "com.yourcompany.yourapp"
        ANDROID_PACKAGE_NAME: "com.yourcompany.yourapp"
        
        # 构建版本配置
        ANDROID_API_LEVEL: 33
        ANDROID_BUILD_TOOLS_VERSION: 33.0.2
        ANDROID_GRADLE_PLUGIN_VERSION: 7.4.2
        JAVA_VERSION: 17
        NODE_VERSION: 18
        FLUTTER_VERSION: 3.16.0
        COCOAPODS_VERSION: 1.14.3

      # 修正后的缓存配置 - 完全符合平台规范
      cache:
        paths:
          - ~/.gradle/caches
          - ~/.gradle/wrapper
          - ~/.npm
          - ~/.cocoapods
          - $FLUTTER_ROOT/.pub-cache
          - ios/Pods

  # Android构建流程
  android-build:
    name: Android Build Workflow
    extends: environment_common
    scripts:
      - name: Set up environment
        script: |
          java -version
          node --version
          npm --version

      - name: Install dependencies
        script: |
          npm ci
          # flutter pub get

      - name: Prepare build assets
        script: |
          mkdir -p android/app/src/main/assets
          npx react-native bundle --platform android --dev false \
            --entry-file index.js \
            --bundle-output android/app/src/main/assets/index.android.bundle \
            --assets-dest android/app/src/main/res
          # flutter build appbundle --release

      - name: Build Android app
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease \
            -PversionCode=$BUILD_NUMBER \
            -PversionName=1.0.$BUILD_NUMBER
          cd ..

    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab

    publishing:
      codemagic:
        - name: Android Release APK
          path: android/app/build/outputs/apk/release/*.apk
        - name: Android App Bundle
          path: android/app/build/outputs/bundle/release/*.aab
      
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_KEY
        track: internal
        in_app_update_priority: 0

  # iOS构建流程
  ios-build:
    name: iOS Build Workflow
    extends: environment_common
    environment:
      xcode: 15.0
      cocoapods: $COCOAPODS_VERSION
    scripts:
      - name: Set up environment
        script: |
          xcodebuild -version
          pod --version
          node --version

      - name: Install dependencies
        script: |
          npm ci
          # flutter pub get
          cd ios
          pod install
          cd ..

      - name: Prepare iOS build
        script: |
          npx react-native config
          # flutter build ios --release --no-codesign

      - name: Build iOS app
        script: |
          cd ios
          xcodebuild archive \
            -workspace YourApp.xcworkspace \
            -scheme YourApp \
            -configuration Release \
            -archivePath build/YourApp.xcarchive \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

          xcodebuild -exportArchive \
            -archivePath build/YourApp.xcarchive \
            -exportPath build \
            -exportOptionsPlist ExportOptions.plist
          cd ..

    artifacts:
      - ios/build/*.ipa
      - ios/build/YourApp.xcarchive.zip

    publishing:
      codemagic:
        - name: iOS IPA
          path: ios/build/*.ipa
      
      app_store_connect:
        api_key_id: $APP_STORE_CONNECT_API_KEY_ID
        api_key_issuer_id: $APP_STORE_CONNECT_API_KEY_ISSUER_ID
        api_key: $APP_STORE_CONNECT_API_KEY
        submit_to_testflight: true
        beta_groups:
          - Internal Testers

  # 每日自动构建
  daily-build:
    name: Daily Scheduled Build
    triggers:
      schedule:
        - cron: "0 12 * * *"
          branch: main
    extends:
      - android-build
      - ios-build
