name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

- name: Ensure gradlew exists
  run: ls -la android || true

- name: Force git mark executable (if present) then chmod
  run: |
    if [ -f android/gradlew ]; then
      git update-index --chmod=+x android/gradlew || true
      chmod +x android/gradlew || true
    else
      echo "android/gradlew not found"
      exit 1
    fi
