name: Android Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:$PATH

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Install Gradle and generate Wrapper
      run: |
        wget https://services.gradle.org/distributions/gradle-7.5.1-bin.zip -O gradle.zip
        unzip gradle.zip -d $HOME/gradle
        export PATH=$HOME/gradle/gradle-7.5.1/bin:$PATH
        gradle -v
        mkdir -p android
        cd android
        gradle wrapper --gradle-version 7.5.1
        ls -l gradle/wrapper/

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install npm dependencies
      run: npm install

    - name: Build Android APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
